// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	entities "BackendCRM/entities"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// ChangeById provides a mock function with given fields: cst, id
func (_m *Repository) ChangeById(cst *entities.Customers, id string) (*entities.Customers, error) {
	ret := _m.Called(cst, id)

	var r0 *entities.Customers
	var r1 error
	if rf, ok := ret.Get(0).(func(*entities.Customers, string) (*entities.Customers, error)); ok {
		return rf(cst, id)
	}
	if rf, ok := ret.Get(0).(func(*entities.Customers, string) *entities.Customers); ok {
		r0 = rf(cst, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Customers)
		}
	}

	if rf, ok := ret.Get(1).(func(*entities.Customers, string) error); ok {
		r1 = rf(cst, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ChangeById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeById'
type Repository_ChangeById_Call struct {
	*mock.Call
}

// ChangeById is a helper method to define mock.On call
//   - cst *entities.Customers
//   - id string
func (_e *Repository_Expecter) ChangeById(cst interface{}, id interface{}) *Repository_ChangeById_Call {
	return &Repository_ChangeById_Call{Call: _e.mock.On("ChangeById", cst, id)}
}

func (_c *Repository_ChangeById_Call) Run(run func(cst *entities.Customers, id string)) *Repository_ChangeById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.Customers), args[1].(string))
	})
	return _c
}

func (_c *Repository_ChangeById_Call) Return(_a0 *entities.Customers, _a1 error) *Repository_ChangeById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ChangeById_Call) RunAndReturn(run func(*entities.Customers, string) (*entities.Customers, error)) *Repository_ChangeById_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields:
func (_m *Repository) FindAll() ([]entities.Customers, error) {
	ret := _m.Called()

	var r0 []entities.Customers
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entities.Customers, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entities.Customers); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Customers)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type Repository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *Repository_Expecter) FindAll() *Repository_FindAll_Call {
	return &Repository_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *Repository_FindAll_Call) Run(run func()) *Repository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Repository_FindAll_Call) Return(_a0 []entities.Customers, _a1 error) *Repository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindAll_Call) RunAndReturn(run func() ([]entities.Customers, error)) *Repository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindBy provides a mock function with given fields: column, value
func (_m *Repository) FindBy(column string, value string) (*entities.Customers, error) {
	ret := _m.Called(column, value)

	var r0 *entities.Customers
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*entities.Customers, error)); ok {
		return rf(column, value)
	}
	if rf, ok := ret.Get(0).(func(string, string) *entities.Customers); ok {
		r0 = rf(column, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Customers)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(column, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindBy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBy'
type Repository_FindBy_Call struct {
	*mock.Call
}

// FindBy is a helper method to define mock.On call
//   - column string
//   - value string
func (_e *Repository_Expecter) FindBy(column interface{}, value interface{}) *Repository_FindBy_Call {
	return &Repository_FindBy_Call{Call: _e.mock.On("FindBy", column, value)}
}

func (_c *Repository_FindBy_Call) Run(run func(column string, value string)) *Repository_FindBy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Repository_FindBy_Call) Return(_a0 *entities.Customers, _a1 error) *Repository_FindBy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindBy_Call) RunAndReturn(run func(string, string) (*entities.Customers, error)) *Repository_FindBy_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: user
func (_m *Repository) Save(user *entities.Customers) error {
	ret := _m.Called(user)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Customers) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type Repository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - user *entities.Customers
func (_e *Repository_Expecter) Save(user interface{}) *Repository_Save_Call {
	return &Repository_Save_Call{Call: _e.mock.On("Save", user)}
}

func (_c *Repository_Save_Call) Run(run func(user *entities.Customers)) *Repository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.Customers))
	})
	return _c
}

func (_c *Repository_Save_Call) Return(_a0 error) *Repository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Save_Call) RunAndReturn(run func(*entities.Customers) error) *Repository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDel provides a mock function with given fields: id
func (_m *Repository) SoftDel(id string) (*entities.Customers, error) {
	ret := _m.Called(id)

	var r0 *entities.Customers
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.Customers, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.Customers); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Customers)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_SoftDel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDel'
type Repository_SoftDel_Call struct {
	*mock.Call
}

// SoftDel is a helper method to define mock.On call
//   - id string
func (_e *Repository_Expecter) SoftDel(id interface{}) *Repository_SoftDel_Call {
	return &Repository_SoftDel_Call{Call: _e.mock.On("SoftDel", id)}
}

func (_c *Repository_SoftDel_Call) Run(run func(id string)) *Repository_SoftDel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Repository_SoftDel_Call) Return(_a0 *entities.Customers, _a1 error) *Repository_SoftDel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_SoftDel_Call) RunAndReturn(run func(string) (*entities.Customers, error)) *Repository_SoftDel_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
